version: "3.4"
services:
  node-exporter:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    container_name: node-exporter
  nix-node-sensor:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node-sensor
    environment:
      PROJECT_UUID: ${LOCAL_PROJECT_UUID}
      SENSOR_NAME: ${LOCAL_SENSOR_NAME}
      RECEIVER_HOST: ${LOCAL_RECEIVER_HOST}
      PROMETHEUS_HOST: ${LOCAL_PROMETHEUS_HOST}
networks:
  default:
    external:
      name: metra-network
