version: "3.4"
services:
  node-exporter:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    container_name: node-exporter
  nix-node-sensor:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nix-node-sensor
    environment:
      METRIX_UUID: ad19118b-dda3-4e5f-ba11-465652df1909
      ADDRESS: udp://metrix-agent:8094